spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_pagamentos # Ajuste conforme seu ambiente
mercadopago:
  token: APP_USR-3130684598119223-010519-2b93b0f96adcbbc4309e0d1cb06549c0-3113708013
  notification-url: https://seusite.com/api/pagamentos/webhook # URL p√∫blica (use ngrok para testar local)
cloud:
  aws:
    sqs:
      queue:
        url: ${SQS_QUEUE_URL} # URL gerada pelo Terraform