spring:
  application:
    name: payment-service
  config:
    import: "aws-parameterstore:/payment-service/"
  data:
    mongodb:
      uri: ${mongodb-uri}
mercadopago:
  token: ${mp-token}
  notification-url: ${mp-notification-url}
  user-id: ${mp-user-id}
cloud:
  aws:
    sns:
      topic:
        arn: ${sns-topic-arn}